name: ProjectHD CI/CD

on :
  push:
    branches:
      - main

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build Web Application Project with Maven
      run: mvn -f ./PROJECTHD install -DskipTests
